### ISSUE TITLE
Spice points to non-existent commit in v1.9_RC

### ISSUE THREAD

**Issue by Roenski** [TheSystemDevelopmentKit/thesdk_template#20]
Clicking spice on https://github.com/TheSystemDevelopmentKit/thesdk_template/tree/v1.9_RC/Entities shows 404 error.

This means that the commit it points to has not been pushed. Therefore, initializing the template repo in v1.9_RC branch fails.

@mkosunen you made the commit that changed it https://github.com/TheSystemDevelopmentKit/thesdk_template/commit/6a5ff76c9b76ca8d71402691c264193e5a12f818 so either you need to push the commit, or then someone needs to revert to an older commit.

**Comment by mkosunen** [comment]
@Roenski Should be OK now.

**Comment by Roenski** [comment]
You pushed to Icarus branch, but I will merge it so no worries, the commit seems to work now anyway. Closed

EDIT: nevermind, you pushed the spice, my mistake. Thanks!
